const { Router } = require('express');

const authRoutes = require('./auth');
const schoolRoutes = require('./schools');
const studentRoutes = require('./students');
const teacherRoutes = require('./teachers');
const classRoutes = require('./classes');
const parentRoutes = require('./parents');
const subjectRoutes = require('./subjects');
const attendanceRoutes = require('./attendance');
const resultRoutes = require('./results');
const feeRoutes = require('./fees');
const timetableRoutes = require('./timetable');
const announcementRoutes = require('./announcements');
const eventRoutes = require('./events');
const permissionRoutes = require('./permissions');
const reportRoutes = require('./reports');
const termRoutes = require('./terms');
const portalRoutes = require('./portal');
const portalAiRoutes = require('./portalAi');
const portalGamesRoutes = require('./portalGames');
const notificationRoutes = require('./notifications');
const libraryRoutes = require('./library');
const certificateRoutes = require('./certificates');
const booksRoutes = require('./books');
const onlineExamsRoutes = require('./onlineExams');
const studentPortalRoutes = require('./studentPortal');
const paymentsRoutes = require('./payments');

const router = Router();

router.use('/auth', authRoutes);
router.use('/schools', schoolRoutes);
router.use('/students', studentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/classes', classRoutes);
router.use('/parents', parentRoutes);
router.use('/subjects', subjectRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/results', resultRoutes);
router.use('/fees', feeRoutes);
router.use('/timetable', timetableRoutes);
router.use('/announcements', announcementRoutes);
router.use('/events', eventRoutes);
router.use('/permissions', permissionRoutes);
router.use('/reports', reportRoutes);
router.use('/terms', termRoutes);
router.use('/portal', portalRoutes);
router.use('/portal', portalAiRoutes);
router.use('/portal/games', portalGamesRoutes);
router.use('/notifications', notificationRoutes);
router.use('/library', libraryRoutes);
router.use('/certificates', certificateRoutes);
router.use('/books', booksRoutes);
router.use('/online-exams', onlineExamsRoutes);
router.use('/student-portal', studentPortalRoutes);
router.use('/payments', paymentsRoutes);

module.exports = router;
